### ISSUE TITLE
sensitive information in ROS v7

### ISSUE THREAD

**Issue by robertogaxiola** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#21]
There is still an issue with the hide-sensitive option, now in 7.1 the export always hide sensitive information by default, you have to use show-sensitive parameter to export those options too, i have manually changed my script in the export section.

**Comment by beeyev** [comment]
Thank you for pointing it out, the issue has been fixed!
https://github.com/beeyev/Mikrotik-RouterOS-automatic-backup-and-update/blob/3b47c497343763777d49b06272a616513f10d8a5/BackupAndUpdate.rsc#L159

**Comment by MrVodinn** [comment]
Hello @beeyev! Thank you very much for your script, it is very helpful. 

Can you please double check store sensitive information? I have updated the script and use "
:local sensetiveDataInConfig true;", but passwords still not included in exported config.

Current RouterOS: 7.1.1 (stable) Dec/21/2021 11:53:05
Current routerboard FW: 7.1.1

P.S. It will be nice to have an information about version of the script in the notification mail.

**Comment by beeyev** [comment]
> Can you please double check store sensitive information? I have updated the script and use " :local sensetiveDataInConfig true;", but passwords still not included in exported config.  

Well, that is strange, it should have worked or failed, lol. I will check it.

> P.S. It will be nice to have an information about version of the script in the notification mail.  

Great idea! Will implement that!

**Comment by beeyev** [comment]
@MrVodinn 
The issue was fixed, and your idea about the script version inside the email was implemented, thank you for collaboration!

**Comment by MrVodinn** [comment]
@beeyev 
I have checked - everything works great.
Passwords are saved in the configuration export file, and recovery from the export file went without any errors on RouterOS 7.1.1.
I also want to note that the value of the field "sensetiveDataInConfig" became true by default, this is a very good solution, especially for beginners.

Thanks a lot again!
